/* DRIVERS */

export const GET_DRIVERS_REQUEST = "GET_DRIVERS_REQUEST"
export const GET_DRIVERS_SUCCESS = "GET_DRIVERS_SUCCESS"
export const GET_DRIVERS_FAIL = "GET_DRIVERS_FAIL"

export const ADD_DRIVER_REQUEST = "ADD_DRIVER_REQUEST"
export const ADD_DRIVER_SUCCESS = "ADD_DRIVER_SUCCESS"
export const ADD_DRIVER_FAIL = "ADD_DRIVER_FAIL"

export const EDIT_DRIVER_REQUEST = "EDIT_DRIVER_REQUEST"
export const EDIT_DRIVER_SUCCESS = "EDIT_DRIVER_SUCCESS"
export const EDIT_DRIVER_FAIL = "EDIT_DRIVER_FAIL"

export const DELETE_DRIVER_REQUEST = "DELETE_DRIVER_REQUEST"
export const DELETE_DRIVER_SUCCESS = "DELETE_DRIVER_SUCCESS"
export const DELETE_DRIVER_FAIL = "DELETE_DRIVER_FAIL"