export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const API_ERROR = "LOGIN_API_ERROR"
export const SET_TOKEN = "LOGIN_SET_TOKEN"
export const SET_USER = "LOGIN_SET_USER"
export const GET_CURRENT_USER = "GET_CURRENT_USER"